lacework-dev/scripts

lw_aws_inventory.sh

@scottford-lw @scarolan @andrewwoj @mikelaramie 
Made a minimal improvement to handle multiple AWS accounts simultaneously. FWIW I removed `region=$1` from some of the individual functions/service calls because it wasn't actually doing anything. Would love to hear everyone's thoughts.

update inventory script to handle multiple accounts

---

test/azure/main.tf

Updated `main.tf` to parameterize passwords due to hitting on a guardrail scan. Note that these resources are temporary for counting/testing purposes but good hygiene is desired.

removed static passwords per eng request

---

pwsh/lw_aws_inventory.ps1

This should bring the powershell script up to parity with bash script. Tested both normal & AWS output with `pwsh` on MacOS.

Add AWS ECS Fargate and Lambda counts to Powershell inventory script

---

scanners/lw_proxy_scanner.sh

Updated proxy scanner bash script that uses proxy scanner against a kube context.

Updating port and moving to folder scanners

---

scanners/lw_proxy_scanner.sh

Better image and tag parsing and curl syntax

---

bash/lw_aws_inventory.sh
pwsh/lw_aws_inventory.ps1

We only want to count ECS Fargate Services & Tasks (not ECS EC2 Services or Tasks). We also only want to count running / active.

AWS Inventory Script (bash + ps) - Better counting of ECS Fargate Services & Tasks

---

scanners/lw_proxy_scanner.sh

Updated kubectl command to address all running pods.
Updated echo output for cleaner stdout.
Updated command line args and script to take scanner to utilize as a command line flag "s". With values of either "proxy" or "inline".

Updated to address all pods and scanner args

---

scanners/lw_proxy_scanner.sh

After testing found several issues. 
Fixes for the same. 
Shortened proxy/inline conditional.

Fixed several issues with command flag handling

---

bash/lw_aws_inventory.sh

"Fixed my stupid mistake with the labmda if statement.  Also changed how the script reports fargate tasks.  The script will now count actual container count in fargate and not just tasks.   Removed the counting of the task definitions

Fixed my stupid if test mistake.  Also updated Fargate Counts.

---

cfg_analyzers/azure/enable_disable_checkers/README.md
cfg_analyzers/azure/enable_disable_checkers/azure-cis-config.py
cfg_analyzers/azure/enable_disable_checkers/pyenv-init.sh
cfg_analyzers/gcp/enable_disable_checkers/README.md
cfg_analyzers/gcp/enable_disable_checkers/gcp-cis-config.py
cfg_analyzers/gcp/enable_disable_checkers/pyenv-init.sh

Adding azure/gcp cfg-analyzer checker bulk enable/disable scripts to our public scripts repo
Signed-off-by: Ross <ross.moles@lacework.net>

(feat): Add cfg-analyzer checker bulk enable/disable scripts

---

scanners/lw_scan_containers_csv.py

Hey team, I re-wrote the script to make logging easier. It'll also make adding new functionality easier too.

Container scanner script re-write

---

cfg_analyzers/azure/enable_disable_checkers/README.md
cfg_analyzers/gcp/enable_disable_checkers/README.md

Signed-off-by: Salim Afiune Maya <afiune@lacework.net>

chore: deprecate CLI Wiki

---

cfg_analyzers/azure/enable_disable_checkers/pyenv-init.sh

pyenv-init.sh echo missing

---

.github/CODEOWNERS

https://lacework.atlassian.net/browse/RAIN-28970
Signed-off-by: Ross <ross.moles@lacework.net>

Add CODEOWNERs file based on contributions

---

bash/lw_aws_agentless_preflight.sh

This script will validate a customer's AWS account to assess common issues that may be encountered when trying to deploy Agentless Workload Scanning.

feat: adding `lw_aws_agentless_preflight.sh` script

---

pwsh/lw_azure_inventory.ps1

Script wasn't working in our env
- Used object collection
- Added fields/output to clarify where resources lived
- May need try/catch where $ErrorAction differs from OS default

fix(script): azure pwsh not working

---

lw-suppressions-migration/migrate.py

Adding command to disable new policies if the legacy ones were disabled.

Adding disabled policies 

---

lw-suppressions-migration/migrate.py

Fixing errors flagged by IDE and updating formatting
Signed-off-by: Ross <ross.moles@lacework.net>

chore: suppression migration formatting and tidy up

---

bash/lw_azure_inventory.sh

In most cases, the AZ cli output goes to json by default. This fix handles situations where the AZ cli output is set to something else.

Forced AZ CLI output to json

---

bash/lw_gcp_inventory.sh

Removed dependency on unstable inventory service.

Rewritten GCP sizing script

---

bash/old-resource-scripts/lw_aws_inventory.sh

Done after request from customer for Q1 renewal.

Backported ability to specify what regions to scan to old aws sizing script

---

lw-oci-integration/.gitignore
lw-oci-integration/README.md
lw-oci-integration/bash/lacework_oci_integration_setup.sh
lw-oci-integration/tf/README.md
lw-oci-integration/tf/main.tf
lw-oci-integration/tf/vars.tfvars.example

add oci content

---

lw-oci-integration/README.md
lw-oci-integration/tf/README.md

Just some light edits for the readmes.

Copyedit for the READMEs

---

lw-oci-integration/tf/README.md

Now includes a section on running the terraform via OCI cloud shell

Extend and improve OCI terraform README

---

code-security/iac/update_custom_policies/README.md

Now the change is released, we can mention the version is v0.3.0

Mention version in IaC policy script README.md

---

lw-oci-integration/usage_metrics/README.md

OCI usage_metrics: Change README to use git clone 

---

test/aws/test.sh

just testing the approval flow here.

fix formatting
